#ifndef DIALOGS_HPP
#define DIALOGS_HPP

INT_PTR CALLBACK    About(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    PaletteDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    GradientDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    FontsDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    FillDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    GridDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    BezierDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    SymmetryDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    PerspectiveDialog(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    PatternDialog(HWND, UINT, WPARAM, LPARAM);

extern HINSTANCE hInst;

#endif